services:
  cratedb:
    image: crate:5.5.0
    container_name: cratedb
    ports:
      - 4200:4200
      - 5432:5432
    restart: always
    volumes:
      - cratedb_data:/data
      - cratedb_config:/crate/config
volumes:
  cratedb_data:
    driver: local
  cratedb_config:
    driver: local